services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
     WG_HOST: vpn.${TRAEFIK_DOMAIN}
     LOG_CONFS: false
    networks:
      - wireguard
    ports:
      # VPN traffic
      - 51820:51820/udp
      # Web UI
      - 51821:51821
    volumes:
      - ./data:/etc/wireguard


networks:
  wireguard:
    name: wireguard