services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      WG_HOST: vpn.${TRAEFIK_DOMAIN:?}
      WG_DEFAULT_ADDRESS: 10.0.1.x
      WG_DEFAULT_DNS: 8.8.8.8, 8.8.4.4
      WG_PERSISTENT_KEEPALIVE: 25
      UI_TRAFFIC_STATS: true
      UI_ENABLE_SORT_CLIENTS: true
      UI_CHART_TYPE: 2 # 1 - line chart | 2 - area chart | 3 - bar chart
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.entrypoints=https
      - traefik.http.routers.wireguard.rule=Host(`wg.${TRAEFIK_DOMAIN:?}`)
      - traefik.http.routers.wireguard.tls=true
      - traefik.http.routers.wireguard.tls.certresolver=cloudflare
      - traefik.http.routers.wireguard.middlewares=authentik@file
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
    networks:
      - traefik
      - wireguard
    ports:
      # VPN traffic
      - 51820:51820/udp
      # Web UI
      # - 51821:51821
    volumes:
      - ./data:/etc/wireguard


networks:
  traefik:
    external: true
  wireguard:
    name: wireguard